src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>black</fullName>
                </value>
                <value>
                    <fullName>white</fullName>
                </value>
                <value>
                    <fullName>red</fullName>
                </value>
                <value>
                    <fullName>silver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Picture_URL__c</fullName>
        <label>Picture URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Family</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product_</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductController.cls
/****************************************************************************************
 * Project Name : The South Face
 * File Name : ProductController
 * Description : 필수작성 
 * Copyright : Copyright ©  JieunSong. All Rights Reserved. 2025
 * Author : 82107
 * Created Date : 2025-12-02 오전 10:46
***********************************************************************************/


public with sharing class ProductController
{

    // 비슷한 상품 가져오기
    @AuraEnabled(Cacheable=true scope='global')
    public static Product__c[] getSimilarProducts(Id productId, Id familyId){
        List<Product__c> similarProdcuts = [
                SELECT Id, Name, Gender__c, Picture_URL__c, fm_imageURL__c, Color__c
                FROM Product__c
                WHERE Product_Family__c = :familyId AND Id != :productId];

        System.debug('similarProducts : ' + similarProdcuts);
        return similarProdcuts;
    }
}